esphome:
  name: ulp-test
  includes:
    - custom_components/ulptest.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ulp-Test Fallback Hotspot"
    password: !secret fallback_password

captive_portal:



custom_component:
- lambda: |-
    auto my_custom = new ulptest();
    return {0,0}; // we get a warning if we dont return anything
